device: CUDA
mode: SLURM
ranks_per_node: 4
num_nodes: 1

slurm:
  qos: regular
  partition: ~
  nodelist: ~
  mem_gb: 80
  timeout_hr: 24
  cpus_per_task: 5
  constraint: gpu
  account: m5024_g #

debug: False
run_dir: /global/homes/y/yuejian/project/MLFF-distill/yuejian/runs
dataloader_workers: 0

omol_path: /pscratch/sd/i/ishan_a/ishan_only/OMOL/
