device: CUDA
mode: SLURM
ranks_per_node: 4
num_nodes: 2

slurm:
  qos: premium
  partition: ~
  nodelist: ~
  mem_gb: 80
  timeout_hr: 11
  cpus_per_task: 5
  constraint: gpu
  exclude: null
  account: m5024_g #

debug: False
run_dir: logs
dataloader_workers: 0

omol_path: /global/cfs/cdirs/m4558/aug_29_first_100ps
