includes:
- configs/MPtrj_fairchem/eSEN-Oam.yml

# trainer: src.distill_trainer.DistillTrainer
trainer: src.labels_trainer.LabelsTrainer

dataset:
  train:
    # teacher_labels_folder: data/labels/SPICE_labels/mace_off_large_SpiceAminos
    # teacher_labels_folder: data/labels/SPICE_labels/EScAIP_SpiceAminos
    # Below is an exmaple of label configs if you want to generate that.
    teacher_checkpoint_path: /home/yuejian/project/MLFF-distill/collection/eSEN/esen_30m_oam.pt
    teacher_labels_folder: /data/yuejian/MLFF_DIST/data/labels/MPtrj_fairchem_labels
    label_force_batch_size: 1
    label_jac_batch_size: 1
    vectorize_teach_jacs: False


loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400

optim:
  force_jac_sample_size: 1
  print_memory_usage: False
  vectorize_jacs: True
  energy_distill_coeff: 0
  finite_differences: True