includes:
  - configs/slurm/regular.yml
logger: 
  name: wandb
  entity: ishan-amin
  project: MD22_JMP

trainer: ocp

dataset:
  train:
    format: lmdb
    src: data/md22/lmdb/buckyball-catcher/train
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy: 
            mean:  -124776.7
            stdev: 0.64662045
        forces: 
            mean: 0
            stdev: 1.0899031
  val:
    src: data/md22/lmdb/buckyball-catcher/val

outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 1
  - forces:
      fn: l2mae
      coefficient: 100
evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
