includes:
- configs/md22/buckyball-catcher/distill/gemnet-dT-small.yml
trainer: ocp
MODELPATH: /data/shared/ishan_stuff/student_checkpoints/distilled/md22
run_name: 2024-11-08-12-13-52-gemSmall-buckyball-dist-jmplarge
init_data_idx: 10
seed: 123
save_freq: 1000
steps: 100000 # 100 ps
nvt: False
integrator_config: {"timestep": 1.0, "temperature": 300., "friction": 0.01}