includes:
- configs/md22/buckyball-catcher/distill/gemnet-T-small.yml
trainer: ocp
MODELPATH: data/student_checkpoints/undistilled/md22 
run_name: 2024-11-08-17-57-20-gemTSmall-buckyball-correctenergynorm # this is the path of the model used to compute energies
jmp:
  checkpoint_path: data/buckyball_catcher_jmp-l.ckpt
  data_path: data/md22
  molecule: buckyball-catcher
  direct_forces: True

init_data_idx: 10
seed: 123
save_freq: 1000
steps: 100000 # 100 ps
nvt: False
integrator_config: {"timestep": 1.0, "temperature": 300., "friction": 0.01}

