includes:
  - configs/slurm/regular.yml
  # - configs/slurm/debug.yml
logger: 
  name: wandb
  project: Ac-Ala3

trainer: ocp

dataset:
  train:
    format: lmdb
    # src: /pscratch/sd/i/ishan_a/MD22/95_lmdb/Ac-Ala3-NHMe/train
    src: /data/shared/MLFF/MD22/95_lmdb/Ac-Ala3-NHMe/train
    # split: 5000
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        # energy:
        #   mean: -26913.953
        #   stdev: 0.35547638
        # forces:
        #   mean: 0
        #   stdev: 1.1291506
        energy: 
            mean:  -26913.953
            # stdev: 0.35547638
        forces: 
            mean: 0
            stdev: 1
  val:
    # src: /pscratch/sd/i/ishan_a/MD22/95_lmdb/Ac-Ala3-NHMe/val
    src: /data/shared/MLFF/MD22/95_lmdb/Ac-Ala3-NHMe/val


outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 1
  - forces:
      fn: l2mae
      coefficient: 100
evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
