run_dir: runs
nodelist: escher
# partition: scavenger 
# qos: scavenger
partition: gpu
qos: gpu
mode: SLURM
device: CUDA
ranks_per_node: 6
dataloader_workers: 0
timeout_hr: 12
debug: False
mem_gb: 50
cpus_per_task: 9
