model: src_v2.backbone.CustomESCNMDBackbone
max_num_elements: 100
sphere_channels: 24 # 32
lmax: 2
mmax: 1 # 2
otf_graph: true
max_neighbors: 30
use_pbc: true
use_pbc_single: true
cutoff: 6
edge_channels: 24 # 32
distance_function: gaussian
num_distance_basis: 128
regress_forces: true
regress_stress: true
direct_forces: true
num_layers: 3 # 4
hidden_channels: 24 # 32
norm_type: rms_norm_sh
act_type: gate
ff_type: spectral
chg_spin_emb_type: rand_emb
cs_emb_grad: true
dataset_list:
  - omol
use_dataset_embedding: false