data_root_dir: /data/yuejian/OMol_subset
run_dir: /home/yuejian/project/MLFF-distill/runs/esen_md_4M
account: ocp
qos: ocp
partition: ocp
mode: LOCAL # LOCAL, SLURM, or SLURM_DDP
device: CUDA
ranks_per_node: 1
dataloader_workers: 0
debug: False
mem_gb: 0
cpus_per_task: 2
nodelist: germain
timeout_hr: 1
