includes:
- configs/MPtrj_fairchem/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    hessian_percent: 1. # 0-1, how many percent of the hessian to use
    # metadata_path: /data/ericqu/mptrj_fair/no_isolated_atoms_c12.0/train/metadata.npz
    subset_indices_path: /home/yuejian/project/MLFF-distill/index_list/n<=10atoms.pt
    subset_val_indices_path: /home/yuejian/project/MLFF-distill/index_list/val_natoms<=10.pt
    teacher_labels_folder: /data/yuejian/MLFF_DIST/data/labels/MPtrj_fairchem_natoms<=10_300k

    
loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 10

optim:
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
  energy_distill_coeff: 0