includes:
  - configs/slurm/premium.yml
logger: 
  name: wandb
  project: MPtrj-Energy-FINAL

trainer: ocp

dataset:
  train:
    no_shuffle: True
    format: lmdb
    src: /data/yuejian/MLFF_DIST/data/MPtrj/MPtrj_separated_all_splits/Perovskites_noIons/train
    key_mapping:
      corrected_total_energy: energy
      force: forces
    transforms:
      normalizer:
        energy: 
          mean: 0
          rmsd: 0.8114597201347351 # ryan's value for MPtrj
        forces: 
          mean: 0
          rmsd: 1 # need this to match mace's value
      # normalizer:
      #   energy: 
      #     mean: 0
      #     rmsd: 0.6274 # eSEN Oam ckpt
      #   forces: 
      #     mean: 0
      #     rmsd: 0.6274 # eSEN Oam ckpt
      # normalizer:
      #   energy: 
      #     mean: 0
      #     rmsd: 0.8125 # eSEN MPtrj ckpt
      #   forces: 
      #     mean: 0
      #     rmsd: 0.8125 # eSEN MPtrj ckpt
      element_references:
        file: configs/MPtrj/element_references.pt
  val:
    src: /data/yuejian/MLFF_DIST/data/MPtrj/MPtrj_separated_all_splits/Perovskites_noIons/val


# dataset:
#   train:
#     no_shuffle: True
#     format: ase_db # {ase_db, lmdb}
#     a2g_args: {r_forces: True, r_stress: True, r_data_keys: ['uncorrected_total_energy']}
#     src: /data/ericqu/mptrj_fair/no_isolated_atoms_c12.0/train/train_mptrj.aselmdb
#     key_mapping:
#       uncorrected_total_energy: energy
#       force: forces
#     transforms:
#       normalizer:
#         energy: 
#           mean: 0
#           rmsd: 0.8114597201347351 # BUG: ryan's value for MPtrj
#         forces: 
#           mean: 0
#           rmsd: 1 # need this to match mace's value
#       element_references:
#         file: /data/ericqu/mptrj_fair/norms-refs/element_references.pt
#   val:
#     src: /data/ericqu/mptrj_fair/no_isolated_atoms_c12.0/val/val_mptrj.aselmdb

outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
evaluation_metrics:
  metrics:
    energy:
      - per_atom_mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
