includes:
  - configs/slurm/premium.yml
logger: 
  name: wandb
  project: MPtrj-Energy-FINAL

trainer: ocp

dataset:
  train:
    no_shuffle: True
    format: lmdb
    src: /data/yuejian/MLFF_DIST/data/MPtrj/MPtrj_separated_all_splits/Perovskites_noIons/train
    key_mapping:
      corrected_total_energy: energy
      force: forces
    transforms:
      normalizer:
        energy: 
          mean: 0
          rmsd: 0.8114597201347351 # ryan's value for MPtrj
        forces: 
          mean: 0
          rmsd: 1 # need this to match mace's value
      element_references:
        file: configs/MPtrj/element_references.pt
  val:
    src: /data/yuejian/MLFF_DIST/data/MPtrj/MPtrj_separated_all_splits/Perovskites_noIons/test


outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
evaluation_metrics:
  metrics:
    energy:
      - per_atom_mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
