includes:
- configs/md22/buckyball-catcher/painn/painn-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_checkpoint_path: data/buckyball-catcher_jmp-s.ckpt
    teacher_labels_folder: labels/jmp-small_buckyball-catcher
    label_force_batch_size: 32
    label_jac_batch_size: 64
    vectorize_teach_jacs: False

outputs:
  final_node_features:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 1
  - forces:
      fn: l2mae
      coefficient: 100
  - final_node_features:
      fn: mse
      coefficient: 0
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400
      reduction: mean_all

optim:
  batch_size: 16
  eval_batch_size: 32
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
