run_dir: /home/ishan-amin/runs
nodelist: germain
partition: gpu
qos: gpu
mode: LOCAL # LOCAL, SLURM, or SLURM_DDP
device: CUDA
ranks_per_node: 1
dataloader_workers: 0
debug: True
mem_gb: 0
cpus_per_task: 9
timeout_hr: 1