snapshot_dir: fm_training/dataset_sync_250225
omol_final_snapshot_dir: omol/250430-release

omc_train:
  splits:
    train:
      src: ${cluster.data_root_dir}/${dataset.snapshot_dir}/csp/250225/train/
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_stress: ${regress_stress}
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omc_energy
    forces: ${omc_forces_key}
    stress: omc_stress
  transforms:
    common_transform:
      dataset_name: omc
    stress_reshape_transform:
      dataset_name: omc

omc_val:
  splits:
    val:
      sample_n: 25000
      src: ${cluster.data_root_dir}/${dataset.snapshot_dir}/csp/250225/val/
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_stress: ${regress_stress}
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omc_energy
    forces: ${omc_forces_key}
    stress: omc_stress
  transforms:
    common_transform:
      dataset_name: omc
    stress_reshape_transform:
      dataset_name: omc

omol_train:
  splits:
    train:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/train
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omol_energy
    forces: ${omol_forces_key}
  transforms:
    common_transform:
      dataset_name: omol

omol_val:
  splits:
    val:
      sample_n: 20000
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
    metal_ligand_ood:
      sample_n: 20000
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/metal_ligand_ood
    val_metal_complexes:
      sample_n: 20000
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - metal_complexes
    val_electrolytes:
      sample_n: 20000
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - elytes
    val_biomolecules:
      sample_n: 20000
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - biomolecules
    val_spice:
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - spice
    val_neutralorganics:
      sample_n: 20000
      src: ${cluster.data_root_dir}/${dataset.omol_final_snapshot_dir}/val
      subset_to:
        - op: in
          metadata_key: data_ids
          rhv:
            - ani2x
            - orbnet_denali
            - geom_orca6
            - trans1x
            - rgd
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omol_energy
    forces: ${omol_forces_key}
  transforms:
    common_transform:
      dataset_name: omol

odac_train:
  splits:
    train:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/odac/250225/train
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: odac_energy
    forces: ${odac_forces_key}
  transforms:
    common_transform:
      dataset_name: odac

odac_val:
  splits:
    val:
      sample_n: 20000
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/odac/250225/val
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: odac_energy
    forces: ${odac_forces_key}
  transforms:
    common_transform:
      dataset_name: odac

omat_train:
  splits:
    train:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/train/rattled-relax
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_stress: ${regress_stress}
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omat_energy
    forces: ${omat_forces_key}
    stress: omat_stress
  transforms:
    common_transform:
      dataset_name: omat
    stress_reshape_transform:
      dataset_name: omat

omat_val:
  splits:
    val:
      sample_n: 25000
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/val/rattled-relax
    test:
      sample_n: 25000
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-1000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-1000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-3000-npt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/aimd-from-PBE-3000-nvt
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-1000
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-1000-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-300
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-300-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-500
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-500-subsampled
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/omat24/test_protostructure/rattled-relax
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_stress: ${regress_stress}
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: omat_energy
    forces: ${omat_forces_key}
    stress: omat_stress
  transforms:
    common_transform:
      dataset_name: omat
    stress_reshape_transform:
      dataset_name: omat

oc20_train:
  splits:
    train:
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/train/all
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/train/md38M
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/train/rattled17M
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20_slabs/train
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20_slabs/val_id
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20_slabs/val_ood
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/multi_adsorbate/250214/train+val
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: oc20_energy
    forces: ${oc20_forces_key}
  transforms:
    common_transform:
      dataset_name: oc20

oc20_val:
  splits:
    val_id:
      sample_n: 25000
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/val/id
    val_ood_both:
      sample_n: 25000
      src:
        - ${cluster.data_root_dir}/${dataset.snapshot_dir}/oc20/val/ood_both
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    energy: oc20_energy
    forces: ${oc20_forces_key}
  transforms:
    common_transform:
      dataset_name: oc20
