data_root_dir: /data/yuejian/OMol_Whole
run_dir: /home/yuejian/project/MLFF-distill/runs/esen_md_4M
account: null
qos: scavenger
partition: scavenger
# qos: gpu
# partition: gpu
mode: SLURM
device: CUDA
ranks_per_node: 2
dataloader_workers: 8 # 8
debug: False
mem_gb: 50
cpus_per_task: 2 # 2
timeout_hr: 1
nodelist: germain
