data_root_dir: /data/yuejian/OMol_Whole
run_dir: /home/yuejian/project/MLFF-distill/runs/esen_md_4M
account: ocp
qos: ocp
mode: LOCAL
device: CUDA
ranks_per_node: 2
dataloader_workers: 0
debug: False
mem_gb: 0
cpus_per_task: 2