defaults: 
 - base_dataset
 - _self_
 
omol_train:
  splits:
    train:
      src: ${cluster.omol_path}/4M/subsets/OMol_subset/protein_ligand_pockets_train_4M
  teacher_labels_folder: ${cluster.omol_path}/4M/subsets/OMol_subset_label_torch_autograd_UMA/protein_ligand_pockets_train_4M/labels

omol_val:
  splits:
    val:
      # sample_n: 2000
      src: ${cluster.omol_path}/4M/subsets/OMol_subset/protein_ligand_pockets_val_small
  teacher_labels_folder: ${cluster.omol_path}/4M/subsets/OMol_subset_label_torch_autograd_UMA/protein_ligand_pockets_train_4M/labels
