# Make sure to run without AMP.
includes:
- configs/Trans1x/transition_states_0.49_0.51/base.yml

model:
  name: painn
  hidden_channels: 128
  num_layers: 4
  num_rbf: 128
  cutoff: 12.0
  max_neighbors: 50
  scale_file: configs/Trans1x/transition_states_0.49_0.51/painn/painn-small-scale.pt
  regress_forces: True
  direct_forces: True
  use_pbc: True
  otf_graph: True
  emb_size_teacher: 256
  teacher_atom_embedding_path: labels/jmp-large_atom_embeddings.npy


optim:
  batch_size: 128
  eval_batch_size: 128
  load_balancing: atoms
  num_workers: 8
  optimizer: AdamW
  optimizer_params: {"eps": 1.e-7, "weight_decay": 0.000002, "amsgrad": True}
  lr_initial: 1.e-3
  scheduler: ReduceLROnPlateau
  patience: 10
  factor: 0.8
  min_lr: 0.000005
  max_epochs: 10000
  ema_decay: 0.999
  clip_grad_norm: 10


