includes:
- configs/MPtrj/Bandgap_greater_5/painn/painn-small.yml

model:
  name: src.models.painn_baseline.PaiNN
  baseline: True
  use_teacher_node_embeddings: False
  use_teacher_atom_embeddings: True
  teacher_atom_embedding_path: data/labels/atom_embeddings/mace_mp0_atom_embeddings.npy
  emb_size_teacher: 256
