device: CUDA
mode: SLURM
ranks_per_node: 2
num_nodes: 1


slurm:
  qos: scavenger  # other options: scavenger and long, also need to set partition to the same thing
  partition: scavenger
  nodelist: escher
  mem_gb: 50
  timeout_hr: 24
  cpus_per_task: 9
  constraint: gpu
  account: m4558_g #

debug: False
run_dir: runs
nodelist: escher
dataloader_workers: 0