run_dir: runs
nodelist: germain
partition: scavenger
qos: scavenger
mode: SLURM
device: CUDA
ranks_per_node: 2
<<<<<<<< HEAD:configs_yj/nersc/protein_ligand_pocket_finite_diff/cluster/Germain.yaml
dataloader_workers: 1
timeout_hr: 120
========
dataloader_workers: 0
timeout_hr: 12
>>>>>>>> fairchemV2:configs/OMol_simplified/cluster/Germain.yaml
debug: False
mem_gb: 50
cpus_per_task: 9
omol_path: /data/ishan-amin/OMOL