device: CUDA
mode: LOCAL
ranks_per_node: 2
num_nodes: 1


slurm:
  qos: gpu
  partition: ~
  nodelist: germain
  mem_gb: 50
  timeout_hr: 24
  cpus_per_task: 9
  constraint: gpu
  account: m4558_g #

debug: False
run_dir: runs
nodelist: germain
dataloader_workers: 4

omol_path: /data/ishan-amin/OMOL