includes:
- configs/SPICE/monomers/gemnet-dT-small.yml

MODELPATH: /data/shared/ishan_stuff/student_checkpoints/spice
run_name: 2024-09-05-00-08-48-monomers-gemSmall
init_data_idx: 10
seed: 123
save_freq: 100
steps: 100
fmax: 0.05
  