includes:
- configs/SPICE/monomers/gemnet-dT-small.yml

checkpoint: data/student_energy_checkpoints/distilled/spice_escaip/Monomers-Gem-EScaip/best_checkpoint.pt
output_folder: data/student_energy_checkpoints/distilled/spice_escaip/
init_data_idx: 10
seed: 30
save_freq: 208
steps: 100000 # 100 ps
nvt: False
integrator_config: {"timestep": 1.0, "temperature": 300., "friction": 0.01}