includes:
- configs/SPICE/monomers/gemnet-dT-small.yml

MODELPATH: /data/shared/ishan_stuff/student_checkpoints/spice
run_name: 2024-09-05-00-08-48-monomers-gemSmall
init_data_idx: 10
seed: 123
save_freq: 1000
steps: 100000 # 100 ps
nvt: False
integrator_config: {"timestep": 1.0, "temperature": 300., "friction": 0.01}