includes:
- configs/SPICE/monomers/gemnet-T-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: data/labels_unlocked/EScAIP_labels/monomers

model:
  name: src.models.gemnet_baseline.GemNetT #gemnet_t_baseline
  baseline: True
  use_teacher_node_embeddings: True
  use_teacher_atom_embeddings: False
  teacher_atom_embedding_path: data/labels_unlocked/EScAIP_labels/escaip_atom_embeddings.npy
  emb_size_teacher: 256

outputs:
  final_node_features:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
      reduction: 
  - forces:
      fn: l2mae
      coefficient: 100
  - final_node_features:
      fn: mse
      coefficient: 10000
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 0

evaluation_metrics:
  metrics:
    energy:
      - per_atom_mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    final_node_features:
      - mse
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
  

optim:
  final_node_distill: True
