includes:
- configs/SPICE/monomers/painn/painn-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: data/labels/SPICE_labels/mace_off_large_SpiceMonomers

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 0
      reduction: 
  - forces:
      fn: l2mae
      coefficient: 0
  - teacher_forces:
      fn: l2mae
      coefficient: 100
  - force_jacs:
      fn: l2mae
      coefficient: 0
