device: CUDA
mode: SLURM
ranks_per_node: 4
num_nodes: 1


slurm:
  qos: long # other options: scavenger and long, also need to set partition to the same thing
  partition: long
  nodelist: germain
  mem_gb: 50
  timeout_hr: 24
  cpus_per_task: 9
  constraint: ~
  account: ~
  exclude: null

debug: False
run_dir: logs
nodelist: germain
dataloader_workers: 0

omol_path: /data/ishan-amin/OMOL/electrolytes_application
