defaults:
  - /distill



starting_checkpoint: /home/yuejian/project/MLFF-distill/collected_ckpt_v2/202506-1015-3606-f206/checkpoints/step_0/inference_ckpt.pt

runner:
  train_eval_unit:
    model:
      _target_: src_v2.dataset_utils.initialize_finetuning_model
      checkpoint_location: ${starting_checkpoint}
