includes:
- configs/SPICE/monomers/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    hessian_percent: 1. # 0-1
    teacher_labels_folder: /data/yuejian/MLFF_DIST/data/labels/SPICE_labels/mace_off_large_SpiceMonomers
    # teacher_labels_folder: /data/yuejian/MLFF_DIST/data/labels/SPICE_labels/EScAIP_SpiceMonomers


loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
      reduction: 
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0

  - force_jacs:
      fn: l2mae
      coefficient: 400

optim:
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
  energy_distill_coeff: 0
  finite_differences: False
