device: CUDA
mode: SLURM
ranks_per_node: 1
num_nodes: 1


slurm:
  qos: long  # other options: scavenger and long, also need to set partition to the same thing
  partition: long
  nodelist: germain
  mem_gb: 50
  timeout_hr: 12
  cpus_per_task: 9
  constraint: null
  exclude: null
  account: null #

debug: False
run_dir: runs
nodelist: germain
dataloader_workers: 0

omol_path: /data/ishan-amin/OMOL