includes:
- configs/md17/ethanol/schnet.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_checkpoint_path: teacher_checkpoints/ethanol_50k_gemnet_t/best_checkpoint.pt
    # teacher_labels_folder: /pscratch/sd/i/ishan_a/labels/ethanol_1k_distributed_test
    teacher_labels_folder: labels/ethanol_50k_gemnet_t_50k_labels
    label_force_batch_size: 32
    label_jac_batch_size: 16
    vectorize_teach_jacs: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 1
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400

optim:
  batch_size: 8
  patience: 30
  eval_batch_size: 32
  force_jac_sample_size: 8
  print_memory_usage: False
  finite_differences: False
  vectorize_jacs: True
  eval_every: 1000
