<<<<<<< HEAD:configs/OMOL_V2_complicated/training_4M/cluster/ada6000_local.yaml
data_root_dir: /data/yuejian/OMol_Whole
run_dir: /home/ishan-amin/MLFF-distill/runs/esen_md_4M
=======
data_root_dir: /data/yuejian/OMol_subset
run_dir: /home/yuejian/project/MLFF-distill/runs/esen_md_4M
>>>>>>> dev_yj_fairchem_v2:configs/OMol_fairchem_v2/training_4M/cluster/ada6000_local.yaml
account: ocp
qos: ocp
partition: ocp
mode: LOCAL # LOCAL, SLURM, or SLURM_DDP
device: CUDA
ranks_per_node: 1
dataloader_workers: 0
debug: False
mem_gb: 0
cpus_per_task: 2
nodelist: germain
timeout_hr: 1
constraint: "volta32gb"
exclude: "learnfair2242,learnfair2109,learnfair1336,learnfair2159,learnfair2150,learnfair2153"
