includes:
- configs/SPICE/solvated_amino_acids/gemnet-dT-small.yml

trainer: worstRow

logger:
  name: wandb
  project: spice-efficient-distill

optim:
  active_learning: True
  worst_rows_lmdb_path: student_checkpoints/worst_rows/gem_solvated_worst_corrected.lmdb
