includes:
- configs/SPICE/solvated_amino_acids/painn/painn-small.yml

MODELPATH: /data/shared/ishan_stuff/student_checkpoints/spice
run_name: 2024-09-15-14-45-36-solvated-Painn-DIST-pbc
init_data_idx: 10
seed: 123
save_freq: 1000
steps: 100000
nvt: True
integrator_config: {"timestep": 1.0, "temperature": 300., "friction": 0.01}