includes:
- configs/SPICE/solvated_amino_acids/gemnet-dT-small.yml

MODELPATH: /data/shared/ishan_stuff/student_checkpoints/spice
run_name: 2024-09-05-13-45-52-solvated-gemSmall-DIST-4s
init_data_idx: 10
seed: 123
save_freq: 1000
steps: 100000 # 100 ps
integrator_config: {"timestep": 1.0, "temperature": 300., "friction": 0.01}