defaults:
  - cluster: Germain_local
  - dataset: OMol
  - element_refs: eSEN_omol
  - tasks: omol_direct
  - _self_

job:
  device_type: ${cluster.device}
  scheduler:
    mode: ${cluster.mode}
    ranks_per_node: ${cluster.ranks_per_node}
    num_nodes: 1
    slurm:
      qos: ${cluster.qos}
      partition: ${cluster.partition}
      nodelist: ${cluster.nodelist}
      mem_gb: ${cluster.mem_gb}
      timeout_hr: ${cluster.timeout_hr}
      cpus_per_task: ${cluster.cpus_per_task}
  debug: ${cluster.debug}
  run_dir: ${cluster.run_dir}
  run_name: eSEN_train_4M
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: ishan-amin
    project: OMOL

cpu_graph: True
max_neighbors: 30
cutoff_radius: 6
max_atoms: 350
normalizer_rmsd: 1.433569
direct_forces_coef: 30
energy_coef: 30
bf16: False

exclude_keys: [
  "id", # only oc20,oc22 have this
  "fid", # only oc20,oc22 have this
  "absolute_idx", # only ani has this
  "target_pos", # only ani has this
  "ref_energy", # only ani/geom have this
  "pbc", # only ani/transition1x have this
  "nads", # oc22
  "oc22", # oc22
  "formation_energy", # spice
  "total_charge", # spice
]

val_dataset:
  _target_: fairchem.core.datasets.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    omol: ${dataset.omol_val}
  combined_dataset_config: { sampling: {type: temperature, temperature: 1.0} }

eval_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${val_dataset}
  batch_sampler_fn:
    _target_: fairchem.core.datasets.samplers.max_atom_distributed_sampler.MaxAtomDistributedBatchSampler
    _partial_: True
    max_atoms: ${max_atoms}
    shuffle: False
    seed: 0
  num_workers: ${cluster.dataloader_workers}
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}
