defaults:
  - cluster: local
  - element_refs: eSEN_omol
  - tasks: omol_direct
  - _self_

job:
  device_type: ${cluster.device}
  scheduler:
    mode: ${cluster.mode}
    ranks_per_node: ${cluster.ranks_per_node}
    num_nodes: ${cluster.num_nodes}
    slurm:
      qos: ${cluster.slurm.qos}
      partition: ${cluster.slurm.partition}
      nodelist: ${cluster.slurm.nodelist}
      mem_gb: ${cluster.slurm.mem_gb}
      timeout_hr: ${cluster.slurm.timeout_hr}
      cpus_per_task: ${cluster.slurm.cpus_per_task}
      constraint: ${cluster.slurm.constraint}
      account: ${cluster.slurm.account}
  debug: ${cluster.debug}
  run_dir: ${cluster.run_dir}
  run_name: eSEN_train_4M
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: ishan-amin
    project: OMOL

cpu_graph: True
max_neighbors: 30
cutoff_radius: 6
max_atoms: 350
normalizer_rmsd: 1.433569
direct_forces_coef: 30
energy_coef: 30
bf16: False

exclude_keys: [
  "id", # only oc20,oc22 have this
  "fid", # only oc20,oc22 have this
  "absolute_idx", # only ani has this
  "target_pos", # only ani has this
  "ref_energy", # only ani/geom have this
  "pbc", # only ani/transition1x have this
  "nads", # oc22
  "oc22", # oc22
  "formation_energy", # spice
  "total_charge", # spice
]


data_root_dir: /data/ishan-amin/OMOL/4M/subsets/OMol_subset
starting_checkpoint: /data/ishan-amin/OMOL/esen_md_direct_all.pt


omol_train:
  src: ${data_root_dir}/protein_core_train_4M
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    # energy: omol_energy
    forces: forces
  transforms:
    common_transform:
      dataset_name: omol

omol_val:
  src: ${data_root_dir}/protein_interface_val
  format: ase_db
  a2g_args:
    molecule_cell_size: 120.0
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
    r_edges: ${cpu_graph}
    radius: ${cutoff_radius}
    max_neigh: ${max_neighbors}
  key_mapping:
    # energy: omol_energy
    forces: forces
  transforms:
    common_transform:
      dataset_name: omol

train_dataset_:
  _target_: fairchem.core.datasets.ase_datasets.AseDBDataset
  config: ${omol_train}

val_dataset_:
  _target_: fairchem.core.datasets.ase_datasets.AseDBDataset
  config: ${omol_val}

train_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${train_dataset_}
  batch_sampler_fn:
    _target_: fairchem.core.datasets.samplers.max_atom_distributed_sampler.MaxAtomDistributedBatchSampler
    _partial_: True
    max_atoms: ${max_atoms}
    shuffle: False
    seed: 0
  num_workers: ${cluster.dataloader_workers}
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

eval_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${val_dataset_}
  batch_sampler_fn:
    _target_: fairchem.core.datasets.samplers.max_atom_distributed_sampler.MaxAtomDistributedBatchSampler
    _partial_: True
    max_atoms: ${max_atoms}
    shuffle: False
    seed: 0
  num_workers: ${cluster.dataloader_workers}
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

# heads:
#   energy:
#     module: fairchem.core.models.uma.escn_md.MLP_Energy_Head
#   forces:
#     module: fairchem.core.models.uma.escn_md.Linear_Force_Head

runner:
  _target_: src_v2.labels_trainer.TeacherLabelGenerator
  train_dataloader: ${train_dataloader}
  eval_dataloader: ${eval_dataloader}
  train_eval_unit:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.MLIPTrainEvalUnit
    job_config: ${job}
    tasks: ${tasks}
    model:
      _target_: src_v2.dataset_utils.initialize_finetuning_model
      checkpoint_location: ${starting_checkpoint}
      use_ema: False
    optimizer_fn:
      _target_: torch.optim.AdamW
      _partial_: true
      lr: 8e-4
      weight_decay: 1e-3
    cosine_lr_scheduler_fn:
      _target_: fairchem.core.units.mlip_unit.mlip_unit._get_consine_lr_scheduler
      _partial_: true
      warmup_factor: 0.2
      warmup_epochs: 0.01
      lr_min_factor: 0.01
      epochs: null
      steps: 100000
    print_every: 10
    clip_grad_norm: 100
    bf16: ${bf16}
  label_folder: ${omol_train.src}/raw_labels
