defaults: 
  - eSEN_train # OTHER OPTIONS: 1. eSEN_train 2. /distill 3. /eSEN_eval 4. /eSEN_labels
  - override cluster: Germain
  - override backbone: eSEN_xtra_small  #Not needed for eval
  - override dataset: protein_ligand_pocket_300 #Solvated
  - _self_

job:
  run_name: ligand_pockets_300

direct_forces_coef: 30
energy_coef:        30
max_atoms: 1000
# hessian_coef:       60
# num_hessian_samples: 3