data_root_dir: /data/yuejian/OMol_subset
run_dir: /home/yuejian/project/MLFF-distill/runs/esen_md_4M
account: null
qos: long
partition: long
# qos: gpu
# partition: gpu
mode: SLURM
device: CUDA
ranks_per_node: 7
dataloader_workers: 8 # 8
debug: False
mem_gb: 50
cpus_per_task: 2 # 2
timeout_hr: 120
nodelist: escher
exclude: null
constraint: null