data_root_dir: /home/yuejian/project/MLFF-distill/runs
run_dir: /home/yuejian/project/MLFF-distill/runs/esen_md_4M
account: ocp
qos: ocp
mode: SLURM
device: CUDA
ranks_per_node: 1
dataloader_workers: 8
debug: False
mem_gb: 0
cpus_per_task: 2