normalizer_rmsd: 0.8367225039962408
regress_stress: true
dataset_name: omol

train_dataset:
  splits:
    train:
      # sample_n: 2000
      src: ${cluster.omol_path}/all_NAPF6/train
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
  # no_shuffle: false
  transforms:
    common_transform:
      dataset_name: ${dataset.dataset_name}
    stress_reshape_transform:
      dataset_name: ${dataset.dataset_name}
  teacher_labels_folder: ${cluster.omol_path}/all_NAPF6/labels

val_dataset:
  splits:
    val:
      src: ${cluster.omol_path}/all_NAPF6/val
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
  # no_shuffle: false
  transforms:
    common_transform:
      dataset_name: ${dataset.dataset_name}
    stress_reshape_transform:
      dataset_name: ${dataset.dataset_name}
  teacher_labels_folder: ${cluster.omol_path}/all_NAPF6/labels
