normalizer_rmsd: 0.8195104628817489
regress_stress: true
dataset_name: omol

train_dataset:
  splits:
    train:
      src: ${cluster.omol_path}/electrolytes_application/aselmdb_data/NAPF6/s1p1/train
  format: ase_db
  transforms:
    common_transform:
      dataset_name: ${dataset.dataset_name}
    stress_reshape_transform:
      dataset_name: ${dataset.dataset_name}

val_dataset:
  splits:
    val:
      src: ${cluster.omol_path}/electrolytes_application/aselmdb_data/NAPF6/s1p1/val
  format: ase_db
  transforms:
    common_transform:
      dataset_name: ${dataset.dataset_name}
    stress_reshape_transform:
      dataset_name: ${dataset.dataset_name}
