normalizer_rmsd: 1.3211587314253261
regress_stress: False
dataset_name: omol

train_dataset:
  splits:
    train:
      src: ${cluster.omol_path}/omol_sodium_elytes/aselmdb_revised/train
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
  # no_shuffle: true
  transforms:
    common_transform:
      dataset_name: ${dataset.dataset_name}
    stress_reshape_transform:
      dataset_name: ${dataset.dataset_name}
  teacher_labels_folder: ${cluster.omol_path}/omol_sodium_elytes/labels

val_dataset:
  splits:
    val:
      sample_n: 2000
      src: ${cluster.omol_path}/omol_sodium_elytes/aselmdb_revised/val
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
  # no_shuffle: true
  transforms:
    common_transform:
      dataset_name: ${dataset.dataset_name}
    stress_reshape_transform:
      dataset_name: ${dataset.dataset_name}
  teacher_labels_folder: ${cluster.omol_path}/omol_sodium_elytes/labels
