normalizer_rmsd: 0.8779600192172669
regress_stress: true
dataset_name: omol

dummy_dataset: ${cluster.omol_path}/electrolytes_application/ablate_dense_sample/sample_5

train_dataset:
  splits:
    train:
      src: /home/yuejian/project/MLFF-distill/OMOL/electrolytes_application/ablate_dense_sample/naotf_lmdbs_323K/unequilibrated/train
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
  no_shuffle: true
  transforms:
    common_transform:
      dataset_name: ${dataset.dataset_name}
    stress_reshape_transform:
      dataset_name: ${dataset.dataset_name}
  teacher_labels_folder: /home/yuejian/project/MLFF-distill/OMOL/electrolytes_application/ablate_dense_sample/sample_80


val_dataset:
  splits:
    val:
      src: /home/yuejian/project/MLFF-distill/OMOL/electrolytes_application/ablate_dense_sample/naotf_lmdbs_323K/unequilibrated/val
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
  no_shuffle: true
  transforms:
    common_transform:
      dataset_name: ${dataset.dataset_name}
    stress_reshape_transform:
      dataset_name: ${dataset.dataset_name}
  teacher_labels_folder: /home/yuejian/project/MLFF-distill/OMOL/electrolytes_application/ablate_dense_sample/sample_80

