defaults:
  - cluster: local
  - dataset: NA_TFSI
  - element_refs: NA_TFSI_refs
  - tasks: omol_stress
  - /base
  - _self_

dataset:
  omol_val:
    splits:
      val:
        sample_n: 200   # ← your new value

runner:
  _target_: fairchem.core.components.evaluate.eval_runner.EvalRunner #fairchem.core.components.train.train_runner.TrainEvalRunner
  dataloader: ${eval_dataloader}
  eval_unit:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.MLIPEvalUnit
    job_config: ${job}
    tasks: ${tasks}
    bf16: ${bf16}
    model:
      _target_: fairchem.core.units.mlip_unit.mlip_unit.load_inference_model
      checkpoint_location: ${cluster.omol_path}/esen_sm_direct_all.pt
      return_checkpoint: False
      use_ema: True
      overrides:
        backbone:
          otf_graph: true
  callbacks:
  - _target_: torchtnt.framework.callbacks.TQDMProgressBar