includes:
- configs/Trans1x/transition_states_0.4_0.6/painn/painn-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: labels/jmp-small_transitionstates_0.4_0.6
loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400
      reduction: mean_all

optim:
  batch_size: 16
  eval_batch_size: 32
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
