includes:
  - configs/slurm/premium.yml
logger: 
  name: wandb
  entity: ishan-amin
  project: MD22_JMP

trainer: ocp

dataset:
  train:
    format: lmdb
    src: data/md22/lmdb/double-walled_nanotube/train
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy: 
            mean:  -338224.16
            stdev: 1.0137014 #3.3810701 # make this change for GemNet-T runs
        forces: 
            mean: 0
            stdev: 1.0137014
  val:
    src: data/md22/lmdb/double-walled_nanotube/test
  test:
    src: data/md22/lmdb/double-walled_nanotube/test
  

outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
