includes:
  - configs/slurm/debug.yml
logger: 
  name: wandb
  project: MPtrj-Energy-20percent

trainer: ocp

dataset:
  train:
    no_shuffle: True # dangerous don't shuffle dataset!, dataloader will shuffle after this

    # fairchem mptrj
    format: ase_db # {ase_db, lmdb}
    a2g_args: {r_forces: True, r_stress: True, r_data_keys: ['uncorrected_total_energy']}
    src: /data/ericqu/mptrj_fair/no_isolated_atoms_c12.0/train/train_mptrj.aselmdb
    # src: /pscratch/sd/y/yuejian/mptrj_fair/no_isolated_atoms_c12.0/train/train_mptrj.aselmdb
    key_mapping:
      uncorrected_total_energy: energy
      force: forces

    # # orig mptrj
    # format: lmdb # {ase_db, lmdb}
    # src: /data/yuejian/MLFF_DIST/data/MPtrj/MPtrj_separated_all_splits/Perovskites_noIons/val
    # key_mapping:
    #   corrected_total_energy: energy
    #   force: forces

    transforms:
      normalizer:
        energy: 
          mean: 0 
          rmsd: 0.8114597201347351 
        forces: 
          mean: 0 
          rmsd: 1 
      element_references:
        file: /data/ericqu/mptrj_fair/norms-refs/element_references.pt
        # file: /pscratch/sd/y/yuejian/mptrj_fair/norms-refs/element_references.pt
  val:
    # # orig mptrj
    # src: /data/yuejian/MLFF_DIST/data/MPtrj/MPtrj_separated_all_splits/Perovskites_noIons/val

    # fairchem mptrj
    # BUG: not sure if need this
    a2g_args: {r_forces: True, r_stress: True, r_data_keys: ['uncorrected_total_energy']}
    key_mapping:
      uncorrected_total_energy: energy
      force: forces
    # definately need this
    src: /data/ericqu/mptrj_fair/no_isolated_atoms_c12.0/val/val_mptrj.aselmdb
    # src: /pscratch/sd/y/yuejian/mptrj_fair/no_isolated_atoms_c12.0/val/val_mptrj.aselmdb
outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
evaluation_metrics:
  metrics:
    energy:
      - per_atom_mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
