defaults:
  - cluster: Germain_local
  - dataset: protein_ligand_pocket_eval
  - element_refs: uma_v1_hof_lin_refs
  - tasks: omol_direct
  - _self_

job:
  device_type: ${cluster.device}
  scheduler:
    mode: ${cluster.mode}
    ranks_per_node: ${cluster.ranks_per_node}
    num_nodes: 1
    slurm:
      qos: ${cluster.qos}
      partition: ${cluster.partition}
      nodelist: ${cluster.nodelist}
      mem_gb: ${cluster.mem_gb}
      timeout_hr: ${cluster.timeout_hr}
      cpus_per_task: ${cluster.cpus_per_task}
  debug: ${cluster.debug}
  run_dir: ${cluster.run_dir}
  run_name: protein_ligand_pockets_train_4M_no_distill
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: ishan-amin
    project: OMOL

cpu_graph: True
max_neighbors: 30
cutoff_radius: 6
max_atoms: 1000
normalizer_rmsd: 1.423
direct_forces_coef: 30
omol_energy_coef: 30

# regress_stress: False
# direct_forces: True

omol_forces_key: forces

exclude_keys: [
  "id", # only oc20,oc22 have this
  "fid", # only oc20,oc22 have this
  "absolute_idx", # only ani has this
  "target_pos", # only ani has this
  "ref_energy", # only ani/geom have this
  "pbc", # only ani/transition1x have this
  "nads", # oc22
  "oc22", # oc22
  "formation_energy", # spice
  "total_charge", # spice
]

val_dataset:
  _target_: fairchem.core.datasets.mt_concat_dataset.create_concat_dataset
  dataset_configs:
    omol: ${dataset.omol_val}
  combined_dataset_config: { sampling: {type: temperature, temperature: 1.0} }

eval_dataloader:
  _target_: fairchem.core.components.common.dataloader_builder.get_dataloader
  dataset: ${val_dataset}
  batch_sampler_fn:
    _target_: fairchem.core.datasets.samplers.max_atom_distributed_sampler.MaxAtomDistributedBatchSampler
    _partial_: True
    max_atoms: ${max_atoms}
    shuffle: False
    seed: 0
  num_workers: ${cluster.dataloader_workers}
  collate_fn:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.mt_collater_adapter
    tasks: ${tasks}
    exclude_keys: ${exclude_keys}

runner:
  _target_: fairchem.core.components.evaluate.eval_runner.EvalRunner #fairchem.core.components.train.train_runner.TrainEvalRunner
  dataloader: ${eval_dataloader}
  eval_unit:
    _target_: fairchem.core.units.mlip_unit.mlip_unit.MLIPEvalUnit
    job_config: ${job}
    tasks: ${tasks}
    model:
      _target_: src_v2.dataset_utils.initialize_finetuning_model
      checkpoint_location: /data/ishan-amin/ESEN_checkpoints/esen_omol/esen_md_direct_all.pt