device: CUDA
mode: SLURM
ranks_per_node: 4
num_nodes: 1

slurm:
  qos: gpu
  partition: ghx4
  nodelist: ~
  mem_gb: 64
  timeout_hr: 12
  cpus_per_task: 16
  constraint: gpu  # Commented out since run2.sh doesn't use this
  account: beyy-dtai-gh
  gpu_bind: "verbose,closest"
  ntasks_per_socket: 1

debug: False
run_dir: logs
dataloader_workers: 0

omol_path: /projects/beye/iamin/distillation_project/
