includes:
- configs/MPTraj/Perovskites/base.yml

loss_functions:
  - energy:
      fn: mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100


model:
  name: schnet
  hidden_channels: 128
  num_filters: 128
  num_interactions: 6
  num_gaussians: 25
  cutoff: 6.0
  use_pbc: True
  otf_graph: True

optim:
  batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  lr_initial: 0.0001
  lr_gamma: 0.1
  optimizer: Adam
  warmup_steps: 5000
  warmup_factor: 0.2
  max_epochs: 2000
  scheduler: ReduceLROnPlateau
  factor: 0.8
  min_lr: 0.000001