includes:
- configs/md22/stachyose/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    # teacher_checkpoint_path: teacher_checkpoints/Ac-Ala3_gem_T_nonNorm_1.5M/best_checkpoint.pt
    # teacher_labels_folder: labels/ac_Ala3_all_gemnet_t_proper
    label_force_batch_size: 32
    label_jac_batch_size: 64
    vectorize_teach_jacs: False

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: .25
  - forces:
      fn: l2mae
      coefficient: 250
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 1000
      reduction: mean_all

optim:
  batch_size: 4
  eval_batch_size: 32
  force_jac_sample_size: 30
  print_memory_usage: False
  vectorize_jacs: True
