includes:
- configs/md22/stachyose/gemnet-dT-smaller.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    # teacher_checkpoint_path: teacher_checkpoints/Ac-Ala3-all-gemT-normOFF-570epochs/best_checkpoint.pt
    # teacher_labels_folder: /pscratch/sd/i/ishan_a/labels/Ac-Ala3-all-gemT-normOFF-570epochs
    label_force_batch_size: 32
    label_jac_batch_size: 64
    vectorize_teach_jacs: False

loss_functions:
  - energy:
      fn: per_atom_mae
      coefficient: 1
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400

optim:
  batch_size: 4
  eval_batch_size: 32
  force_jac_sample_size: 12
  print_memory_usage: False
  vectorize_jacs: True
