data_root_dir: /data/yuejian/OMol_subset
account: null
run_dir: runs
nodelist: germain
partition: gpu # scavenger if you want more but want to be upended.
qos: gpu 
mode: LOCAL # LOCAL, SLURM, or SLURM_DDP
device: CUDA
ranks_per_node: 1
dataloader_workers: 1
debug: False
mem_gb: 0
cpus_per_task: 9
timeout_hr: 1
