defaults:
  - _self_
  - io: default
  - conformers: default
  - model: uma
  - minimisation@local_min: uma
  - minimisation@global_min: uma
  - energy_eval: default
  - experiment: null

seed: -1
threshold: 16.1
numThreads: 0
