includes:
- configs/OMol/train_4M/base.yml

model:
  name: hydra
  _target_: fairchem.core.models.base.HydraModel
  pass_through_head_outputs: true
  otf_graph: true
  backbone:
    model: fairchem.core.models.uma.escn_md.eSCNMDBackbone
    max_num_elements: 100
    sphere_channels: 128
    lmax: 4
    mmax: 2
    otf_graph: true
    max_neighbors: 30
    use_pbc: true
    use_pbc_single: true
    cutoff: 6
    edge_channels: 128
    distance_function: gaussian
    num_distance_basis: 128
    regress_forces: true
    regress_stress: false
    direct_forces: true
    num_layers: 10
    hidden_channels: 128
    norm_type: rms_norm_sh
    act_type: gate
    ff_type: spectral
    chg_spin_emb_type: rand_emb
    cs_emb_grad: true
    dataset_list:
      - omol
    use_dataset_embedding: false

  heads:
    energy:
      module: fairchem.core.models.uma.escn_md.MLP_Energy_Head
    forces:
      module: fairchem.core.models.uma.escn_md.Linear_Force_Head

optim:
  batch_size: 8
  eval_batch_size: 8
  num_workers: 8
  lr_initial: 0.0002
  optimizer: AdamW
  
  # temporary solution
  optimizer_params:
    weight_decay: 0.001
  scheduler: ReduceLROnPlateau
  patience: 5
  factor: 0.8
  min_lr: 0.000001  

  # max_epochs: 1000
  # ema_decay: 0.999
  # clip_grad_norm: 10
  # scheduler: LambdaLR
  # scheduler_params:
  #   lambda_type: cosine
  #   warmup_factor: 0.2
  #   warmup_epochs: 277
  #   lr_min_factor: 0.01
  #   epochs: 83370
  #   lr: 0.0002
  #   lr_lambda: [0.5, 0.5]
  
  max_epochs: 30
  clip_grad_norm: 100
  ema_decay: 0.999
  eval_every: 5000
  load_balancing: atoms
  use_denoising_pos: true
  denoising_pos_params:
    prob: 0.0
    fixed_noise_std: true
    std: 0.1
    num_steps: 50
    std_low: 0.01
    std_high: 0.5
  denoising_pos_coefficient: 10
