normalizer_rmsd: 0.871026713903
regress_stress: true
dataset_name: omol

dummy_dataset: ${cluster.omol_path}/electrolytes_application/ablate_dense_sample/sample_5

train_dataset:
  splits:
    train:
      src: /global/homes/y/yuejian/project/MLFF-distill/yuejian/OMOL/electrolyte_application/ablate_dense_sample/napf6_unequilibrated/train
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
  no_shuffle: true
  transforms:
    common_transform:
      dataset_name: ${dataset.dataset_name}
    stress_reshape_transform:
      dataset_name: ${dataset.dataset_name}
  teacher_labels_folder: ${cluster.omol_path}/electrolytes_application/labels/NAPF6/s1p1

val_dataset:
  splits:
    val:
      src: /global/homes/y/yuejian/project/MLFF-distill/yuejian/OMOL/electrolyte_application/ablate_dense_sample/napf6_unequilibrated/val
  format: ase_db
  a2g_args:
    r_energy: True
    r_forces: True
    r_data_keys: ['spin', 'charge']
  no_shuffle: true
  transforms:
    common_transform:
      dataset_name: ${dataset.dataset_name}
    stress_reshape_transform:
      dataset_name: ${dataset.dataset_name}
  teacher_labels_folder: ${cluster.omol_path}/electrolytes_application/labels/NAPF6/s1p1
