defaults: 
 - base_dataset
 - _self_
 
omol_train:
  splits:
    train:
        src: ${cluster.omol_path}/TOY/ligand_pocket_300/train
  teacher_labels_folder: ${cluster.omol_path}/TOY/labels/ligand_pocket_300/

omol_val:
  splits:
    val:
      src: ${cluster.omol_path}/TOY/ligand_pocket_300/val
  teacher_labels_folder: ${cluster.omol_path}/TOY/labels/ligand_pocket_300/
