defaults: 
 - base_dataset
 - _self_
 
omol_train:
  splits:
    train:
      src: ${cluster.omol_path}/4M/subsets/OMol_subset/protein_ligand_pockets_train_4M
  teacher_labels_folder: ${cluster.omol_path}/4M/subsets/FINAL_LABELS/ligand_pocket
  

omol_val:
  splits:
    val:
      sample_n: 2000
      src: ${cluster.omol_path}/4M/subsets/OMol_subset/protein_ligand_pockets_val
  teacher_labels_folder: ${cluster.omol_path}/4M/subsets/FINAL_LABELS/ligand_pocket
