defaults: 
 - base_dataset
 - _self_
 
omol_train:
  splits:
    train:
      src: ${cluster.omol_path}/TOY/solvated/train
  teacher_labels_folder:  ${cluster.omol_path}/TOY/labels/EScAIP_SpiceAminos
  a2g_args:
    molecule_cell_size: ~      # ← this sets it to None
    r_data_keys: ~
omol_val:
  splits:
    val:
      src: ${cluster.omol_path}/TOY/solvated/val
  teacher_labels_folder:  ${cluster.omol_path}/TOY/labels/EScAIP_SpiceAminos
  a2g_args:
    molecule_cell_size: ~       # ← this sets it to None
    r_data_keys: ~
