defaults: 
 - base_dataset
 - _self_
 
omol_train:
  splits:
    train:
      src: /data/ishan-amin/OMOL/TOY/solvated/train
  teacher_labels_folder:  /data/ishan-amin/OMOL/TOY/labels/EScAIP_SpiceAminos
  diverse_atoms_path: /home/christine/MLFF-distill/diverse_idxs_solvated_eval.pt
  use_diverse_atoms: False
  a2g_args:
    molecule_cell_size: ~      # ← this sets it to None
    r_data_keys: ~
omol_val:
  splits:
    val:
      src: /data/ishan-amin/OMOL/TOY/solvated/val
  teacher_labels_folder:  /data/ishan-amin/OMOL/TOY/labels/EScAIP_SpiceAminos
  diverse_atoms_path: /home/christine/MLFF-distill/diverse_idxs_solvated_eval.pt
  use_diverse_atoms: False
  a2g_args:
    molecule_cell_size: ~       # ← this sets it to None
    r_data_keys: ~
