defaults: 
 - base_dataset
 - _self_
 
omol_train:
  splits:
    train:
      src: /data/ishan-amin/OMOL/TOY/solvated/train
  teacher_labels_folder:  data/labels/SPICE_labels/EScAIP_SpiceAminos
  a2g_args:
    molecule_cell_size: ~      # ← this removes it
    r_data_keys: ~
omol_val:
  splits:
    val:
      src: /data/ishan-amin/OMOL/TOY/solvated/val
  teacher_labels_folder:  data/labels/SPICE_labels/EScAIP_SpiceAminos
  a2g_args:
    molecule_cell_size: ~      # ← this removes it
    r_data_keys: ~
