defaults: 
 - base_dataset
 - _self_
 
omol_train:
  splits:
    train:
      src: ${cluster.omol_path}/4M/subsets/OMol_subset/protein_interface_train_4M
  teacher_labels_folder:  ${cluster.omol_path}/4M/subsets/OMol_subset_label_finite_difference/protein_interface_train_4M/final_labels
omol_val:
  splits:
    val:
      # sample_n: 2000
      src: ${cluster.omol_path}/4M/subsets/OMol_subset/protein_interface_val_first_300
  teacher_labels_folder:  ${cluster.omol_path}/4M/subsets/OMol_subset_label_finite_difference/protein_interface_train_4M/final_labels
